spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false

app:
  frontend:
    allowed-origin: ${FRONTEND_ALLOWED_ORIGIN}

logging:
  level:
    root: INFO
    com.example.customermanagement: INFO

